version: '3'
services:
  # nginx
  web:
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - '8000:80'
    links:
      - app
    restart: always
  # php
  app:
    build:
      context: ./docker/php71/
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php71/php.ini:/usr/local/etc/php/php.ini
    links:
      - db
  # DB
  db:
    build:
      context: ./docker/mysql/
      dockerfile: Dockerfile
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: homestead_password
  php-cli:
    build:
      context: ./docker/php71/
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php71/php.ini:/usr/local/etc/php/php.ini
    links:
      - db
